#Version Checking

In [2]:
import sys 
import numpy as np
print("Python Version:", sys.version, '\n')
print("Numpy Version: ", np.__version__)

Python Version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)] 

Numpy Version:  1.26.4


# Why do we like numpy?

Numpy is a great library with many, many functions that extend it well beyond normal Python. We're going to focus on some of the primary functions that we use all the time. 

Also note that Pandas is pretty much just numpy with column names (and some SQL seasoning) in a lot of ways, so anything we can do to a numpy array we can usually do with a Pandas column. A prominent exception: matrix math doesn't work well in pandas.

### Get some data (we'll just use some random data)

In [6]:
import numpy as np

In [7]:
data = np.random.uniform(size=10000)
data_as_list = data.tolist()

In [8]:
data.shape

(10000,)

### Broadcasting

If we want to perform a mathematical operation on a list, we have to explicitly loop through the list. If we want to act on an array, we can just treat it like a single object and the operation is "broadcast" to all of the members of the array. It's LIGHTNING fast. Let's see it in action.

In [10]:
new_data = data + 2

In [11]:
for added, raw in zip(new_data[:10],data):
    print(added, raw)

2.523284178887322 0.5232841788873224
2.3877749915812485 0.3877749915812486
2.5687112200372737 0.5687112200372737
2.6331736444699807 0.6331736444699809
2.175769917917013 0.1757699179170128
2.6786471780014924 0.6786471780014924
2.5362154854672876 0.5362154854672877
2.2148786556718907 0.21487865567189057
2.743590572552587 0.7435905725525871
2.6639702021726825 0.6639702021726825


What do I mean when I say "lightning fast"?

In [13]:
%%timeit
new_list = [x+2 for x in data_as_list]

325 μs ± 9.47 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
%%timeit
new_data2 = data + 2

3 μs ± 31.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Filtering

One of the great things about Pandas is the ability to quickly filter your data. Turns out that's because we're working with numpy arrays. Let's check out filtering on arrays - note that we're going to make a condition and each value in the array will be `True` or `False` based on whether it actually passes the condition.

In [16]:
new_data > 2.5

array([ True, False,  True, ...,  True, False, False])

Once we have the filter, if we ask the array to adjust itself based on that filter, it will automatically only keep the rows that are True.

In [18]:
np.sum(new_data > 2.5)

4992

In [19]:
new_data[new_data > 2.5].shape

(4992,)

In [20]:
new_data[new_data > 1]

array([2.52328418, 2.38777499, 2.56871122, ..., 2.81548244, 2.17657356,
       2.24150959])

We can also filter on any data source that has the same length as the data we're filtering. So for instance, if we make a condition on `data` which is equivalent to `new_data - 2`, we can still filter `new_data` the same way. That's possible because data has the same length.

In [22]:
new_data[data > 0.5]

array([2.52328418, 2.56871122, 2.63317364, ..., 2.71473821, 2.85273811,
       2.81548244])

#### Exercise:

Write a function that takes in two arrays and a value. The first array is a data array, the second is a 1D array, and the value should be numeric.

We want to use broadcasting and filtering to return the rows of the first array, that correspond to indexes where the second array has a value larger than the user provided value. We also want to add 2 to the values in that row.

Example:

```
x1 = np.array([[1,2],[3,4],[5,6]])
x2 = np.array([1, 2, 3])
value = 1.5

my_function(x1, x2, value)
----
> array([[5, 6],
>        [7, 8]])
```

In [24]:
# complete exercise here

### Reorganization

`numpy` also allows us to quick reorganize our array. Let's see a simple working example. By providing a list of "how to align the indexes" we can rearrange the data. 

In [27]:
a = np.array([10,20,30,40,50])
a[[1,0,2,3,4]]

array([20, 10, 30, 40, 50])

### Random number draws

`numpy` also has a great series of tools for generating random numbers effectively. Let's see a few in action (we'll use matplotlib to visualize.

In [30]:
import seaborn
import matplotlib.pyplot as plt
%matplotlib inline
#plt.style.use("seaborn")

def plot_hist(x, bins=None):
    plt.figure(dpi=100)
    plt.hist(x, bins=bins);

In [31]:
x = np.random.uniform(0,10,size=500)
plot_hist(x)    

In [32]:
x = np.random.normal(3,1,size=20000)
plot_hist(x, bins=100)

In [33]:
x = np.random.poisson(2, size=20000)
plot_hist(x, bins=20)

### Matrix Multiplication

Doing matrix multiplication programmatically is usually a hassel. `numpy` makes that simple. There are two methods for doing that: `numpy` treats `@` as meaning "do the matrix multiplication".

In [36]:
mat_a = np.random.uniform(size=(2,4))
mat_b = np.random.uniform(size=(4,3))

mat_a

array([[0.68316479, 0.73026151, 0.27368272, 0.26805285],
       [0.32031739, 0.65831526, 0.70982168, 0.1126259 ]])

In [37]:
mat_a@mat_b

array([[1.5658888 , 1.14083346, 1.38709737],
       [1.29449167, 1.00847357, 1.23191899]])

It also throws an error if the multiplication can't happen.

Try `mat_b@mat_a`

In [39]:
# mat_b@mat_a

You can also use `np.dot` to do the multiplication. However, be careful with this, as it also computes the actual dot product of vectors. It tries to be smart about how it does that, so it usually does a good job. 

In [41]:
np.dot(mat_a, mat_b)

array([[1.5658888 , 1.14083346, 1.38709737],
       [1.29449167, 1.00847357, 1.23191899]])

Vector dot product example:

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

`numpy` also knows about basic matrix stuff like transposes, etc. It also has a ton of cool linear algebra stuff under `np.linalg` but we're going to skip over that for now.

In [45]:
mat_a

array([[0.68316479, 0.73026151, 0.27368272, 0.26805285],
       [0.32031739, 0.65831526, 0.70982168, 0.1126259 ]])

In [46]:
mat_a.T

array([[0.68316479, 0.32031739],
       [0.73026151, 0.65831526],
       [0.27368272, 0.70982168],
       [0.26805285, 0.1126259 ]])

### Vectorization

And here's why `numpy` is a magical beast. We can take many common things and convert them into a "vectorized" process - meaning that we do the same thing over the whole dataset using advanced broadcasting. So for instance, let's look at adding a vector to a matrix (we're going to add this vector to each row) 

In [49]:
mat_a.T + np.array([1,2])

array([[1.68316479, 2.32031739],
       [1.73026151, 2.65831526],
       [1.27368272, 2.70982168],
       [1.26805285, 2.1126259 ]])

`numpy` noticed that the column lengths matched and automatically adjusted to adding the whole vectors.

What do we think the below code will do?

In [51]:
mat_a - np.array([1,2,3,4])

array([[-0.31683521, -1.26973849, -2.72631728, -3.73194715],
       [-0.67968261, -1.34168474, -2.29017832, -3.8873741 ]])

We can use that to do things like calculating the distance between a single vector and a whole table of vectors. Let's see that in action.

**Let's find the vector distance between a bunch of vectors and one vector**

In [54]:
new_vec = np.array([1,2])
all_vecs = np.random.uniform(size=(100,2))

If we were doing it for one vector:

In [56]:
x = all_vecs[0]
np.sqrt((new_vec[0] - x[0])**2 + (new_vec[1] - x[1])**2)

1.9276717947121422

Now let's do it for all 100 vectors:

In [58]:
np.sqrt(np.sum((all_vecs - new_vec)**2, axis=1))[:10]

array([1.92767179, 1.26308543, 1.64363667, 1.729733  , 1.18215118,
       1.35467728, 1.7914549 , 1.42061691, 1.34200768, 1.44397037])

Many, many, many processes can be vectorized... and it can be a huge time saver on large datasets. Let's see the difference.

In [60]:
%%timeit
output = []
for x in all_vecs:
    dist = np.sqrt((new_vec[0] - x[0])**2 + (new_vec[1] - x[1])**2)
    output.append(dist)

155 μs ± 7.46 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
%%timeit
np.sqrt(np.sum((all_vecs - new_vec)**2, axis=1))

6.42 μs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


What about at a larger scale than 100?

In [63]:
all_vecs = np.random.uniform(size=(10000,2))

In [64]:
%%timeit
output = []
for x in all_vecs:
    dist = np.sqrt((new_vec[0] - x[0])**2 + (new_vec[1] - x[1])**2)
    output.append(dist)

15.1 ms ± 496 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
np.sqrt(np.sum((all_vecs - new_vec)**2, axis=1))

In [ ]:
import time
list_timing = []
for num_vecs in np.linspace(10,10000,100):
    all_vecs = np.random.uniform(size=(int(num_vecs),2)).tolist()
    # To measure when we start our process
    start = time.time()
    
    # The actual process
    output = []
    for x in all_vecs:
        dist = np.sqrt((new_vec[0] - x[0])**2 + (new_vec[1] - x[1])**2)
        output.append(dist)
        
    # Figure out when the process was done and 
    # keep track of how long it took
    end = time.time()
    list_timing.append((num_vecs, end - start))

In [ ]:
array_timing = []
for num_vecs in np.linspace(10,10000,100):
    all_vecs = np.random.uniform(size=(int(num_vecs),2))
    # To measure when we start our process
    start = time.time()
    
    # The actual process
    output = np.sqrt(np.sum((all_vecs - new_vec)**2, axis=1))
        
    # Figure out when the process was done and 
    # keep track of how long it took
    end = time.time()
    array_timing.append((num_vecs, end - start))

In [ ]:
plt.figure(dpi=150)
list_X, list_times = zip(*list_timing)
array_X, array_times = zip(*array_timing)

plt.plot(list_X, list_times, 'r', label="Lists")
plt.plot(array_X, array_times,'b', label='Arrays')
plt.xlabel("Number of Vectors")
plt.ylabel("Computation Time")
plt.legend();

Hard to see what's happening there. Let's look on a log scale.

In [ ]:
plt.figure(dpi=150)
list_X, list_times = zip(*list_timing)
array_X, array_times = zip(*array_timing)

plt.plot(list_X, list_times, 'r', label="Lists")
plt.plot(array_X, array_times,'b', label='Arrays')
plt.yscale('log')
plt.xlabel("Number of Vectors")
plt.ylabel("Computation Time")
plt.legend();