# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
array_1_dim = np.array([1,2,3])
#print(array_1_dim)
# Create a 2-dimensional NumPy array using np.array()
array_2_dim = np.array([[1,2,3],[4,5,6]])
#print(array_2_dim)

# Create a 3-dimensional Numpy array using np.array()
array_3_dim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#print(array_3_dim)


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
ar_1d_shape      = array_1_dim.shape
ar_1d_dim        = array_1_dim.ndim
ar_1d_data_type  = array_1_dim.dtype
ar_1d_size       = array_1_dim.size
ar_1d_array_type = type(array_1_dim)
print(ar_1d_array_type)

<class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
ar_2d_shape     = array_2_dim.shape
ar_2d_dim       = array_2_dim.ndim
ar_2d_data_type = array_2_dim.dtype
ar_2d_size      = array_2_dim.size
ar_2d_array_type = type(array_2_dim)
print(ar_2d_array_type)

<class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
ar_3d_shape     = array_3_dim.shape
ar_3d_dim       = array_3_dim.ndim
ar_3d_data_type = array_3_dim.dtype
ar_3d_size      = array_3_dim.size
ar_3d_array_type = type(array_3_dim)
print(ar_3d_data_type)

int32


In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pn
df = pn.DataFrame(array_2_dim)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [9]:
# Create an array of shape (10, 2) with only ones
ar_ones = np.ones((10,2))
print(array_ones)

NameError: name 'array_ones' is not defined

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
ar_zeros = np.zeros((7,2,3))
print(ar_zeros)

In [ ]:
# Create an array within a range of 0 and 100 with step 3
ar_arange = np.arange(0,100,3)
print(ar_arange)

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ar_random = np.random.randint(0,10,size=(7,2))
print(ar_random)

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ar_random_float = np.random.rand(3,5)
print(ar_random_float)

In [34]:
# Set the random seed to 42
ar_random_set = np.random.seed(42)
print(ar_random_set)
# Create a random array of numbers between 0 & 10 of size (4, 6)
ar_random_array = np.random.randint(0,10,size=(4,6))
print(ar_random_array)

None
[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

The numbers are not the same because Random generates random numbers, and they differ each time

In [44]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

ar_random_array_2 = np.random.randint(1,10,size=(3,7))
print(ar_random_array_2)

# Find the unique numbers in the array you just created
ar_unique = np.unique(ar_random_array_2)
print(ar_unique)

[[9 7 9 8 2 1 7]
 [7 8 5 3 8 6 3]
 [1 3 5 3 1 5 7]]
[1 2 3 5 6 7 8 9]


In [56]:
# Find the 0'th index of the latest array you created
ar_random_array_2_0_index = ar_random_array_2[0]
print(ar_random_array_2_0_index)

[9 7 9 8 2 1 7]


In [58]:
# Get the first 2 rows of latest array you created
ar_random_array_2_2_row = ar_random_array_2[0:2,]
print(ar_random_array_2_2_row)

[[9 7 9 8 2 1 7]
 [7 8 5 3 8 6 3]]


In [66]:
# Get the first 2 values of the first 2 rows of the latest array
ar_random_array_2_2_values = ar_random_array_2[0:2,0:2]
print(ar_random_array_2_2_values)

[[9 7]
 [7 8]]


In [74]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ar_random_2 = np.random.randint(0,10,size=(3,5))
print(ar_random_2)
ar_ones_2   = np.ones((3,5))
print(ar_ones_2)

[[3 0 0 9 3]
 [6 1 2 0 4]
 [0 7 0 0 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [78]:
# Add the two arrays together
ar_add = ar_random_2 + ar_ones_2
print(ar_add)

[[ 4.  1.  1. 10.  4.]
 [ 7.  2.  3.  1.  5.]
 [ 1.  8.  1.  1.  2.]]


In [80]:
# Create another array of ones of shape (5, 3)
ar_ones_3   = np.ones((5,3))
print(ar_ones_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [82]:
# Try add the array of ones and the other most recent array together
ar_add_all = ar_ones_3 + ar_add

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

The two matrices cannot be added because the dimensions are different. To solve this problem, we need to either adjust or change the dimensions of one of them so that the dimensions match, allowing us to perform the addition.

In [84]:
# Create another array of ones of shape (3, 5)
ar_ones_4   = np.ones((3,5))
print(ar_ones_4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [88]:
# Subtract the new array of ones from the other most recent array
ar_subtract = ar_ones_4-ar_ones_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [90]:
# Multiply the ones array with the latest array
ar_multiply = ar_ones_4 * ar_ones_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [94]:
# Take the latest array to the power of 2 using '**'
ar_power = ar_ones_3**2
print(ar_power)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [96]:
# Do the same thing with np.square()
ar_square = np.square(ar_ones_3)
print(ar_square)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [98]:
# Find the mean of the latest array using np.mean()
ar_mean = np.mean(ar_ones_3)
print(ar_mean)

1.0


In [100]:
# Find the maximum of the latest array using np.max()
ar_max = np.max(ar_ones_3)
print(ar_max)

1.0


In [102]:
# Find the minimum of the latest array using np.min()
ar_min = np.min(ar_ones_3)
print(ar_min)

1.0


In [104]:
# Find the standard deviation of the latest array
ar_std = np.std(ar_ones_3)
print(ar_std)

0.0


In [106]:
# Find the variance of the latest array
ar_var = np.var(ar_ones_3)
print(ar_var)

0.0


In [114]:
# Reshape the latest array to (3, 5, 1)
ar_reshape = ar_ones_3.reshape((3,5,1))
print(ar_reshape)

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [116]:
# Transpose the latest array
ar_Transpose = ar_ones_3.T
print(ar_Transpose)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


What does the transpose do?
Transposes the rows into columns and the columns into rows in the matrix.

In [120]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar_random_3 = np.random.randint(0,10,size=(3,3))
ar_random_4 = np.random.randint(0,10,size=(3,2))
print(ar_random_3)
print(ar_random_4)

[[0 5 7]
 [4 3 1]
 [5 5 0]]
[[8 5]
 [2 3]
 [3 2]]


In [122]:
# Perform a dot product on the two newest arrays you created
ar_dot = ar_random_3.dot(ar_random_4)
print(ar_dot)

[[31 29]
 [41 31]
 [50 40]]


In [124]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar_random_5 = np.random.randint(0,10,size=(4,3))
ar_random_6 = np.random.randint(0,10,size=(4,3))
print(ar_random_5)
print(ar_random_6)

[[9 2 2]
 [3 6 3]
 [8 0 7]
 [6 1 7]]
[[0 8 8]
 [1 6 9]
 [2 6 9]
 [8 3 0]]


In [126]:
# Perform a dot product on the two newest arrays you created
ar_dot_2 = ar_random_5.dot(ar_random_6)
print(ar_dot_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
The number of columns in the first matrix must equal the number of rows in the second matrix.

In [128]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ar_dot_3 = ar_random_5.dot(ar_random_6.T)
print(ar_dot_3)

[[32 39 48 78]
 [72 66 69 42]
 [56 71 79 64]
 [64 75 81 51]]


Notice how performing a transpose allows the dot product to happen.

Why is this?  Because the number of columns in the first matrix is equal to the number of rows in the second matrix.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [130]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar_random_7 = np.random.randint(0,10,size=(4,3))
ar_random_8 = np.random.randint(0,10,size=(4,3))
print(ar_random_7)
print(ar_random_8)

[[1 0 4]
 [4 6 8]
 [8 2 2]
 [2 3 7]]
[[5 7 0]
 [7 3 0]
 [7 3 5]
 [7 3 2]]


In [134]:
# Compare the two arrays with '>'
ar_compare = ar_random_7 > ar_random_8
print(ar_compare)

[[False False  True]
 [False  True  True]
 [ True False False]
 [False False  True]]


What happens when you compare the arrays with `>`?
It will compare each element of the first matrix with the corresponding element of the second matrix. If it is greater, the condition will be met, and the result will be true. If it is smaller, the condition will not be met, and the result will be false.

In [136]:
# Compare the two arrays with '>='
ar_compare_2 = ar_random_7 >= ar_random_8
print(ar_compare_2)

[[False False  True]
 [False  True  True]
 [ True False False]
 [False  True  True]]


In [140]:
# Find which elements of the first array are greater than 7
ar_compare_3 = ar_random_7 > 7
print(ar_compare_3)

[[False False False]
 [False False  True]
 [ True False False]
 [False False False]]


In [142]:
# Which parts of each array are equal? (try using '==')
ar_compare_4 = ar_random_7 == ar_random_8
print(ar_compare_4)

[[False False False]
 [False False False]
 [False False False]
 [False  True False]]


In [176]:
# Sort one of the arrays you just created in ascending order
ar_ascending_sort = ar_random_7.sort(axis=1)
print(ar_ascending_sort)

None


In [178]:
# Sort the indexes of one of the arrays you just created
ar_indexes_sort = np.argsort(ar_random_7)
print(ar_indexes_sort)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [156]:
# Find the index with the maximum value in one of the arrays you've created
ar_max_index = np.argmax(ar_random_7)
print(ar_max_index)

5


In [160]:
# Find the index with the minimum value in one of the arrays you've created
ar_min_index = np.argmin(ar_random_7)
print(ar_min_index)

0


In [164]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
ar_max_axis_index = np.argmax(ar_random_7,axis=1)
print(ar_max_axis_index)

[2 2 2 2]


In [166]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
ar_min_axis_index = np.argmax(ar_random_7,axis=0)
print(ar_min_axis_index)

[1 1 1]


In [170]:
# Create an array of normally distributed random numbers
ar_normally_distributed = np.random.normal(5,1,10)
print(ar_normally_distributed)

[4.04010537 6.10492822 5.6342403  8.06109521 3.68142984 5.72038724
 5.31589091 5.05928128 5.91051222 4.97027464]


In [172]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ar_linspace = np.linspace(1,100,10)
print(ar_linspace)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


### Well done !